### ISSUE TITLE
Break time input locks up upon input of minus

### ISSUE THREAD

**Issue by Jimmysaaan** [CoffeeCoder1015/Study-clock#2]
Break time input locks up upon input of minus

## Steps to reproduce:

1. Hit `-`
2. Input numbers
3. Observe

-----------

1. Input numbers
2. Hit `-`
3. Continue inputting numbers
5. Observe

**Comment by Jimmysaaan** [comment]
The same applies to `+`

**Comment by CoffeeCoder1015** [comment]
Was not fixed, amended commit incomming
